In [41]:
import pandas as pd
import numpy as np

In [42]:
df=pd.read_csv("DateFruit_Dataset.csv")

In [43]:
df.head() #34 Featues and one output/category

,AREA,PERIMETER,MAJOR_AXIS,MINOR_AXIS,ECCENTRICITY,EQDIASQ,SOLIDITY,CONVEX_AREA,EXTENT,ASPECT_RATIO,...,KurtosisRR,KurtosisRG,KurtosisRB,EntropyRR,EntropyRG,EntropyRB,ALLdaub4RR,ALLdaub4RG,ALLdaub4RB,Class
0,422163,2378.908,837.8484,645.6693,0.6373,733.1539,0.9947,424428,0.7831,1.2976,...,3.2370,2.9574,4.2287,-59191263232,-50714214400,-39922372608,58.7255,54.9554,47.8400,BERHI
1,338136,2085.144,723.8198,595.2073,0.5690,656.1464,0.9974,339014,0.7795,1.2161,...,2.6228,2.6350,3.1704,-34233065472,-37462601728,-31477794816,50.0259,52.8168,47.8315,BERHI
2,526843,2647.394,940.7379,715.3638,0.6494,819.0222,0.9962,528876,0.7657,1.3150,...,3.7516,3.8611,4.7192,-93948354560,-74738221056,-60311207936,65.4772,59.2860,51.9378,BERHI
3,416063,2351.210,827.9804,645.2988,0.6266,727.8378,0.9948,418255,0.7759,1.2831,...,5.0401,8.6136,8.2618,-32074307584,-32060925952,-29575010304,43.3900,44.1259,41.1882,BERHI
4,347562,2160.354,763.9877,582.8359,0.6465,665.2291,0.9908,350797,0.7569,1.3108,...,2.7016,2.9761,4.4146,-39980974080,-35980042240,-25593278464,52.7743,50.9080,42.6666,BERHI

In [44]:
df.isnull().sum()  #already pre processed, no data cleaning required

AREA             0
PERIMETER        0
MAJOR_AXIS       0
MINOR_AXIS       0
ECCENTRICITY     0
EQDIASQ          0
SOLIDITY         0
CONVEX_AREA      0
EXTENT           0
ASPECT_RATIO     0
ROUNDNESS        0
COMPACTNESS      0
SHAPEFACTOR_1    0
SHAPEFACTOR_2    0
SHAPEFACTOR_3    0
SHAPEFACTOR_4    0
MeanRR           0
MeanRG           0
MeanRB           0
StdDevRR         0
StdDevRG         0
StdDevRB         0
SkewRR           0
SkewRG           0
SkewRB           0
KurtosisRR       0
KurtosisRG       0
KurtosisRB       0
EntropyRR        0
EntropyRG        0
EntropyRB        0
ALLdaub4RR       0
ALLdaub4RG       0
ALLdaub4RB       0
Class            0
dtype: int64

In [45]:
df["Class"].unique()

<StringArray>
['BERHI', 'DEGLET', 'DOKOL', 'IRAQI', 'ROTANA', 'SAFAVI', 'SOGAY']
Length: 7, dtype: str

In [46]:
X=df.drop("Class", axis=1)
y=df["Class"]

In [72]:
X.shape

(898, 34)

In [47]:
X.head()

,AREA,PERIMETER,MAJOR_AXIS,MINOR_AXIS,ECCENTRICITY,EQDIASQ,SOLIDITY,CONVEX_AREA,EXTENT,ASPECT_RATIO,...,SkewRB,KurtosisRR,KurtosisRG,KurtosisRB,EntropyRR,EntropyRG,EntropyRB,ALLdaub4RR,ALLdaub4RG,ALLdaub4RB
0,422163,2378.908,837.8484,645.6693,0.6373,733.1539,0.9947,424428,0.7831,1.2976,...,0.6019,3.2370,2.9574,4.2287,-59191263232,-50714214400,-39922372608,58.7255,54.9554,47.8400
1,338136,2085.144,723.8198,595.2073,0.5690,656.1464,0.9974,339014,0.7795,1.2161,...,0.4134,2.6228,2.6350,3.1704,-34233065472,-37462601728,-31477794816,50.0259,52.8168,47.8315
2,526843,2647.394,940.7379,715.3638,0.6494,819.0222,0.9962,528876,0.7657,1.3150,...,0.9183,3.7516,3.8611,4.7192,-93948354560,-74738221056,-60311207936,65.4772,59.2860,51.9378
3,416063,2351.210,827.9804,645.2988,0.6266,727.8378,0.9948,418255,0.7759,1.2831,...,1.8028,5.0401,8.6136,8.2618,-32074307584,-32060925952,-29575010304,43.3900,44.1259,41.1882
4,347562,2160.354,763.9877,582.8359,0.6465,665.2291,0.9908,350797,0.7569,1.3108,...,0.8865,2.7016,2.9761,4.4146,-39980974080,-35980042240,-25593278464,52.7743,50.9080,42.6666

In [48]:
# Encoding the Output Values

from sklearn.preprocessing import LabelEncoder

le=LabelEncoder()
y=le.fit_transform(y)

In [49]:
y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3, 3, 3,
       3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
       3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
       3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 4,
       4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4,
       4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4,
       4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4,
       4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4,
       4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4,
       4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4,
       4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4,
       4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5,
       5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5,
       5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5,
       5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5,
       5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5,
       5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5,
       5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5,
       5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5,
       5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5,
       5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6,
       6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6,
       6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6,
       6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6,
       6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6])

In [50]:
# Splitting the data

from sklearn.model_selection import train_test_split

X_train,X_test,y_train,y_test=train_test_split(
    X,y,test_size=0.2,random_state=42
)

In [73]:
X_train.shape

(718, 34)

In [51]:
X_train.head()

,AREA,PERIMETER,MAJOR_AXIS,MINOR_AXIS,ECCENTRICITY,EQDIASQ,SOLIDITY,CONVEX_AREA,EXTENT,ASPECT_RATIO,...,SkewRB,KurtosisRR,KurtosisRG,KurtosisRB,EntropyRR,EntropyRG,EntropyRB,ALLdaub4RR,ALLdaub4RG,ALLdaub4RB
880,364338,2385.5110,849.6287,548.4377,0.7638,681.0944,0.9874,368969,0.7596,1.5492,...,0.3835,2.5413,2.7010,4.7956,-45702238208,-31309285376,-31791349760,54.5422,46.1706,47.5687
740,343379,2360.4670,919.1130,479.2314,0.8533,661.2138,0.9657,355591,0.6926,1.9179,...,0.8084,13.2536,10.8915,5.0327,-6173152768,-10177111040,-13946608640,20.5354,27.7553,33.2095
231,80044,1059.0460,378.1419,270.6614,0.6983,319.2416,0.9883,80990,0.7521,1.3971,...,-0.1599,2.2247,2.4509,2.2165,-9834114048,-9082079232,-8377428480,54.3915,53.0591,50.5000
388,394009,2279.7581,770.8477,654.0494,0.5292,708.2852,0.9945,396190,0.7632,1.1786,...,1.6654,5.7796,9.1424,7.8056,-18411845632,-23242752000,-23591233536,34.5177,38.9835,38.4695
118,242874,1843.9160,647.9982,479.8817,0.6720,556.0906,0.9906,245181,0.7818,1.3503,...,-0.3694,2.4534,2.2759,2.5079,-46650236928,-40748339200,-32199612416,66.5225,62.6833,56.9092

In [53]:
#Scaling the Input Data

from sklearn.preprocessing import StandardScaler

scaler=StandardScaler()

X_train_scaled=scaler.fit_transform(X_train)
X_test_scaled=scaler.transform(X_test)

In [60]:
type(X_train_scaled)
# type(y_train)

numpy.ndarray

### ANN

In [63]:
#Creating Tensors / Converting our data into Tensors

import torch
import torch.nn as nn
import torch.optim as optim
from torch.utils.data import DataLoader, TensorDataset

In [64]:
X_train_tensor=torch.tensor(X_train_scaled, dtype=torch.float32)
y_train_tensor=torch.tensor(y_train, dtype=torch.long)

X_test_tensor=torch.tensor(X_test_scaled, dtype=torch.float32)
y_test_tensor=torch.tensor(y_test, dtype=torch.long)

In [65]:
# Creat Batches with the help of TensorDataset and tensor Dataloader for training

train_dataset=TensorDataset(X_train_tensor,y_train_tensor)
test_dataset=TensorDataset(X_test_tensor,y_test_tensor)

In [66]:
train_loader=DataLoader(train_dataset, batch_size=32,shuffle=True)
test_loader=DataLoader(test_dataset, batch_size=32)

In [68]:
# Defining Our ANN Model


class ANN(nn.Module):
    def __init__(self):
        super(ANN,self).__init__()

        self.model=nn.Sequential(
            #1st Hidden Layer
            nn.Linear(X_train.shape[1], 64),
            nn.ReLU(),

            #2nd Hidden Layer
            nn.Linear(64,64),
            nn.ReLU(),

            #Output Layer
            nn.Linear(64,7)
        )

    def forward(self,x):
        return self.model(x)

In [71]:
# Building Our ANN Model

model=ANN()

# loss, Optimizer
criterion=nn.CrossEntropyLoss()
optimizer=optim.Adam(model.parameters())

In [74]:
# Training Our ANN Model , we wont perform any validation since the dataset only has 800 values

best_validation_loss=float("inf")

epochs=100

for epoch in range(epochs):
    model.train()
    
    running_loss=0.0 #Total Training Loss 1 Epoch
    
    for xb,yb in train_loader:
        #xb= Features of 1 batch, yb= Outputs/Labels of 1 batch

        optimizer.zero_grad()
        
        outputs=model(xb) #Forward Propagation...Predicted Outputs for this Batch
        loss=criterion(outputs, yb)  #Computing the loss
        loss.backward()  #Backward Propagation
        optimizer.step() #Updating the Parameters

        running_loss+=loss.item()  #Loss is a tensor value that is converted into a python float value

    train_loss=running_loss/len(train_loader)

    print(f"Epoch={epoch+1}/{epochs} ==> Training Loss: {train_loss}")

Epoch=1/100 ==> Training Loss: 1.7557829514793728
Epoch=2/100 ==> Training Loss: 1.169723674007084
Epoch=3/100 ==> Training Loss: 0.7511415559312572
Epoch=4/100 ==> Training Loss: 0.5549814325311909
Epoch=5/100 ==> Training Loss: 0.4534849375486374
Epoch=6/100 ==> Training Loss: 0.38335001533446106
Epoch=7/100 ==> Training Loss: 0.3413242172935735
Epoch=8/100 ==> Training Loss: 0.31058190633421356
Epoch=9/100 ==> Training Loss: 0.27849067877168243
Epoch=10/100 ==> Training Loss: 0.26867768621963
Epoch=11/100 ==> Training Loss: 0.24817119571177856
Epoch=12/100 ==> Training Loss: 0.23578852641841638
Epoch=13/100 ==> Training Loss: 0.2343013830806898
Epoch=14/100 ==> Training Loss: 0.21539344606192215
Epoch=15/100 ==> Training Loss: 0.2051928739832795
Epoch=16/100 ==> Training Loss: 0.19311192242995553
Epoch=17/100 ==> Training Loss: 0.18383872120276742
Epoch=18/100 ==> Training Loss: 0.17847081338581833
Epoch=19/100 ==> Training Loss: 0.17372837695090668
Epoch=20/100 ==> Training Loss: 0.17211934081886127
Epoch=21/100 ==> Training Loss: 0.16115312403796808
Epoch=22/100 ==> Training Loss: 0.15453629179493242
Epoch=23/100 ==> Training Loss: 0.14846204302233199
Epoch=24/100 ==> Training Loss: 0.14739071674968884
Epoch=25/100 ==> Training Loss: 0.14122966077664625
Epoch=26/100 ==> Training Loss: 0.14210600454522215
Epoch=27/100 ==> Training Loss: 0.1378827127425567
Epoch=28/100 ==> Training Loss: 0.1326844110761
Epoch=29/100 ==> Training Loss: 0.13193241603996442
Epoch=30/100 ==> Training Loss: 0.12962058834407642
Epoch=31/100 ==> Training Loss: 0.12446114161740178
Epoch=32/100 ==> Training Loss: 0.12439677200239638
Epoch=33/100 ==> Training Loss: 0.11625922536072524
Epoch=34/100 ==> Training Loss: 0.1194949611697508
Epoch=35/100 ==> Training Loss: 0.11221493545757688
Epoch=36/100 ==> Training Loss: 0.11035819222097812
Epoch=37/100 ==> Training Loss: 0.1062531518223493
Epoch=38/100 ==> Training Loss: 0.10915359061049379
Epoch=39/100 ==> Training Loss: 0.10392703682832095
Epoch=40/100 ==> Training Loss: 0.10808848881203195
Epoch=41/100 ==> Training Loss: 0.09932481303163197
Epoch=42/100 ==> Training Loss: 0.09541401153673297
Epoch=43/100 ==> Training Loss: 0.09264263980414557
Epoch=44/100 ==> Training Loss: 0.09054417438481165
Epoch=45/100 ==> Training Loss: 0.0892622341685321
Epoch=46/100 ==> Training Loss: 0.08449472551760466
Epoch=47/100 ==> Training Loss: 0.08949349269918773
Epoch=48/100 ==> Training Loss: 0.08367596372314122
Epoch=49/100 ==> Training Loss: 0.08051525048263695
Epoch=50/100 ==> Training Loss: 0.08208189232517844
Epoch=51/100 ==> Training Loss: 0.07826699988673562
Epoch=52/100 ==> Training Loss: 0.07739378187967383
Epoch=53/100 ==> Training Loss: 0.07811053186331106
Epoch=54/100 ==> Training Loss: 0.08287371168641941
Epoch=55/100 ==> Training Loss: 0.07977702881654967
Epoch=56/100 ==> Training Loss: 0.07645763140981612
Epoch=57/100 ==> Training Loss: 0.0768332359502497
Epoch=58/100 ==> Training Loss: 0.0716944380622843
Epoch=59/100 ==> Training Loss: 0.07021913645060165
Epoch=60/100 ==> Training Loss: 0.06737968856063874
Epoch=61/100 ==> Training Loss: 0.06914860135673181
Epoch=62/100 ==> Training Loss: 0.06726764579829962
Epoch=63/100 ==> Training Loss: 0.07524560262327609
Epoch=64/100 ==> Training Loss: 0.07093712501227856
Epoch=65/100 ==> Training Loss: 0.06631579841284649
Epoch=66/100 ==> Training Loss: 0.06925411830129831
Epoch=67/100 ==> Training Loss: 0.06118863379663747
Epoch=68/100 ==> Training Loss: 0.05976965699506843
Epoch=69/100 ==> Training Loss: 0.05901657773748688
Epoch=70/100 ==> Training Loss: 0.05789536768165619
Epoch=71/100 ==> Training Loss: 0.05892522762651029
Epoch=72/100 ==> Training Loss: 0.057410534916688565
Epoch=73/100 ==> Training Loss: 0.05589715031016132
Epoch=74/100 ==> Training Loss: 0.058697150372292686
Epoch=75/100 ==> Training Loss: 0.06974049349841864
Epoch=76/100 ==> Training Loss: 0.05692330274083044
Epoch=77/100 ==> Training Loss: 0.05166977534637503
Epoch=78/100 ==> Training Loss: 0.0515605882620034
Epoch=79/100 ==> Training Loss: 0.050652203352554985
Epoch=80/100 ==> Training Loss: 0.049737774949196886
Epoch=81/100 ==> Training Loss: 0.04715955540861772
Epoch=82/100 ==> Training Loss: 0.051635617471259575
Epoch=83/100 ==> Training Loss: 0.04551026188646969
Epoch=84/100 ==> Training Loss: 0.047995899479998196
Epoch=85/100 ==> Training Loss: 0.0429139733719437
Epoch=86/100 ==> Training Loss: 0.04529907622212625
Epoch=87/100 ==> Training Loss: 0.04734269513384155
Epoch=88/100 ==> Training Loss: 0.04431811209930026
Epoch=89/100 ==> Training Loss: 0.043478682718199234
Epoch=90/100 ==> Training Loss: 0.047546717054817986
Epoch=91/100 ==> Training Loss: 0.04252311579235222
Epoch=92/100 ==> Training Loss: 0.044716870695676494
Epoch=93/100 ==> Training Loss: 0.04096403064044273
Epoch=94/100 ==> Training Loss: 0.03683587056382195
Epoch=95/100 ==> Training Loss: 0.03514735971617958
Epoch=96/100 ==> Training Loss: 0.039908031528086765
Epoch=97/100 ==> Training Loss: 0.03513715158054686
Epoch=98/100 ==> Training Loss: 0.03356342839644007
Epoch=99/100 ==> Training Loss: 0.034470498744074415
Epoch=100/100 ==> Training Loss: 0.03215819706573435

In [81]:
#Here instead of taking the best model based on the least training loss we are just going 
# to consider the final model that is ready after 100 epochs, i.e we are going to assume whatever model we
# got after 100 epochs as our best model


# Evaluate or Testing our Model

model.eval()

total=0
correct=0

with torch.no_grad():

    for xb,yb in test_loader:
        outputs=model(xb) # example output ==> [0.2,0.5,1.3,-0.6,1.2,-1.8.2.3] 7 Output Values
        max_val, predicted_class = torch.max(outputs,1)

        correct+=(predicted_class==yb).sum().item() #for one batch
        total+=yb.size(0) #actual number of samples in each batch

print("Total Values:", total)
print("Correct Values:", correct)
print("Accuracy Score:",(correct/total)*100)

Total Values: 180
Correct Values: 167
Accuracy Score: 92.77777777777779

In [76]:
y_test.shape

(180,)